name: systemq

services:
  redis:
    image: redis:7-alpine
    container_name: systemq-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.tmp/redis:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always

  bullboard:
    image: venatum/bull-board:latest
    container_name: systemq-bullboard
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_PREFIX=bull
    depends_on:
      - redis
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    container_name: systemq-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - ./.tmp/redisinsight:/data
    depends_on:
      - redis
    restart: always

networks:
  default:
    name: systemq-network